In [7]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Print array type:",type(arr))
print("Shape 2 rows 3 coloumns",arr.shape)
print("Dimensions:",arr.ndim)
print(arr.size)
print(arr.dtype)



Print array type: <class 'numpy.ndarray'>
Shape 2 rows 3 coloumns (3, 3)
Dimensions: 2
9
int32


In [43]:
c=np.zeros([2,3])
a=np.array([[2,2,2],[3,3,3]],dtype='float')
print(a)
b=np.arange(0,10,5)
print(b)
d=np.linspace(1,10,5)
print(d)

arr=np.array([[1,2,3,4],[6,7,8,9],[11,12,13,14]])
newarr=arr.reshape(2,2,3)
print(newarr)

flat=arr.flatten()#it will convert 2d array to 1d array
print(flat)

[[2. 2. 2.]
 [3. 3. 3.]]
[0 5]
[ 1.    3.25  5.5   7.75 10.  ]
[[[ 1  2  3]
  [ 4  6  7]]

 [[ 8  9 11]
  [12 13 14]]]
[ 1  2  3  4  6  7  8  9 11 12 13 14]


In [65]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
temp=arr[:3,::3]
print(temp)

[[ 1  4]
 [ 5  8]
 [ 9 12]]
