In [2]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Print array type:",type(arr))
print("Shape 2 rows 3 coloumns",arr.shape)
print("Dimensions:",arr.ndim)
print(arr.size)
print(arr.dtype)



Print array type: <class 'numpy.ndarray'>
Shape 2 rows 3 coloumns (3, 3)
Dimensions: 2
9
int32


In [43]:
c=np.zeros([2,3])
a=np.array([[2,2,2],[3,3,3]],dtype='float')
print(a)
b=np.arange(0,10,5)
print(b)
d=np.linspace(1,10,5)
print(d)

arr=np.array([[1,2,3,4],[6,7,8,9],[11,12,13,14]])
newarr=arr.reshape(2,2,3)
print(newarr)

flat=arr.flatten()#it will convert 2d array to 1d array
print(flat)

[[2. 2. 2.]
 [3. 3. 3.]]
[0 5]
[ 1.    3.25  5.5   7.75 10.  ]
[[[ 1  2  3]
  [ 4  6  7]]

 [[ 8  9 11]
  [12 13 14]]]
[ 1  2  3  4  6  7  8  9 11 12 13 14]


In [76]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
temp=arr[:3,::3]
print(temp)
index=arr[[0,1,2]]
print(index)
cond=arr>0
temp=arr[cond]
print(temp)

[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [86]:
#operations on single element in an array:
a=np.array([1,2,3,4])
print(a+1)
print(a-1)
print(a*2)
print(a**2)
a=a*2
print(a)
print(a.T)

[2 3 4 5]
[0 1 2 3]
[2 4 6 8]
[ 1  4  9 16]
[2 4 6 8]
[2 4 6 8]


In [97]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.sum())
print(arr.cumsum())
print(arr.max())
print("col wise",arr.max(axis=1))
print("row wise",arr.max(axis=0))
print("col wise",arr.min(axis=1))
print("row wise",arr.min(axis=0))

[[1 2 3 4]
 [5 6 7 8]]
36
[ 1  3  6 10 15 21 28 36]
8
col wise [4 8]
row wise [5 6 7 8]
col wise [1 5]
row wise [1 2 3 4]


In [9]:
arr1=np.array([[1,2],[5,6]])
arr2=np.array([[1,2],[5,6]])
#matrix multiplication:
print(arr1.dot(arr2))
print(arr1*arr2,arr1+arr2,arr1-arr2)



[[11 14]
 [35 46]]
[[ 1  4]
 [25 36]] [[ 2  4]
 [10 12]] [[0 0]
 [0 0]]


In [11]:
#exponent:
a=np.array([1,2,3])
print(np.sqrt(a))
print(np.exp(a))

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]


In [18]:
#array sort:
a=np.array([[1,2,0,3],[5,6,7,8],[-1,-2,-3,-4]])
print(np.sort(a,axis=None))
#array row wise sort:
print(np.sort(a,axis=1))
#array coloumn wise sort:
print(np.sort(a,axis=0))
#coloumn wise merge sort:

dtypes=[('name','S10'),('grad_year',int),('cgpa',float)]
values=[('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
#creating array:
arr=np.array(values,dtype=dtypes)
print(np.sort(arr,order='name'))

[-4 -3 -2 -1  0  1  2  3  5  6  7  8]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [-4 -3 -2 -1]]
[[-1 -2 -3 -4]
 [ 1  2  0  3]
 [ 5  6  7  8]]
[(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
